# Generated by Django 5.1.4 on 2025-01-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
