# Generated by Django 5.0 on 2025-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0005_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password_reset_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
