# Generated by Django 5.1.4 on 2025-01-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.ImageField(upload_to='category_img'),
        ),
    ]
