# Generated by Django 5.0 on 2025-01-10 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCategory', '0004_rename_subcategory_name_subcategory_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_set', to='ProductCategory.category'),
        ),
    ]
