# Generated by Django 5.0 on 2025-01-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCategory', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
