# Generated by Django 5.1.4 on 2025-01-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCategory', '0006_alter_category_category_name_and_more'),
        ('Products', '0003_alter_brand_brand_name_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_set', to='ProductCategory.subcategory'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage_set', to='Products.product'),
        ),
    ]
